'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {rotate,ports} from '@/lib/game';
import {illuminate,type JourneyPuzzle} from '@/lib/journey';

export function MechanicLesson({stage,open,onClose}:{stage:number;open:boolean;onClose:()=>void}){
 const [turned,setTurned]=useState(false);
 const paired=stage>=61,color=stage>=41,split=stage>=21;
 const p:JourneyPuzzle={id:0,size:2,stage,paceSeconds:0,initial:[14,12,1,3],solution:[14,12,1,3],path:[0,1,3,2],par:1,locked:stage<21?[0]:[],filters:color?(paired?{0:'amber',1:'violet'}:{1:'amber'}):{},receivers:split?[{at:2,color:color&&paired?'amber':'mint'},...(color?[{at:3,color:paired?'violet' as const:'amber' as const}]:[])]:[],lesson:''};
 const board=[...p.solution];if(!turned)board[1]=rotate(board[1]);const signal=illuminate(board,p);
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="game-dialog"><DialogTitle>{paired?'Two prisms, two colors':color?'Change the light’s color':split?'One beam, two destinations':'Work around a fixed tile'}</DialogTitle><DialogDescription>{paired?'A prism changes the light passing through it. Light A with amber and V with violet.':color?'P·A changes passing light to amber. Route it to the A receiver.':split?'Every connected opening carries light. A three-way tile can feed a receiver and the exit together.':'A padlock tile cannot rotate. Its neighbors must connect to its fixed openings.'}</DialogDescription><div className="lesson-board" aria-label="Practice board; light enters top left and exits bottom right">{board.map((mask,i)=><button key={i} disabled={i!==1} className={signal.lit.has(i)?'lesson-lit':''} onClick={()=>setTurned(v=>!v)} aria-label={`Practice row ${Math.floor(i/2)+1}, column ${i%2+1}; ${ports(mask)}${i===1?'; tap to connect the corner':''}`}><svg viewBox="0 0 100 100" aria-hidden="true">{[1,2,4,8].filter(b=>mask&b).map(b=><path key={b} d={`M50 50 L${b===2?100:b===8?0:50} ${b===1?0:b===4?100:50}`}/>)}</svg><span>{p.locked.includes(i)?'🔒':p.filters[i]?'P·'+(p.filters[i]==='amber'?'A':'V'):''}{p.receivers.filter(r=>r.at===i).map(r=>r.color==='mint'?'◇':r.color==='amber'?'A':'V')}</span></button>)}</div><p role="status">{signal.solved?'Connected. Both the exit and required receivers have light.':'Tap the top-right corner to complete this practice path.'}</p><button className="primary-button" onClick={onClose}>{signal.solved?'Try the puzzle':'Continue to puzzle'}</button><p className="helper-note">Practice does not affect your score. You can replay this lesson anytime.</p></DialogContent></Dialog>;
}
