'use client';
import {useEffect,useState} from 'react';
import type {usePlayer} from './usePlayer';
import {SignInProviders} from './SignInProviders';
import {StardustShop} from './StardustShop';
import {dustForStreak} from '@/lib/currency';
export function PlayerPanel({player,onPreview,onSample}:{player:ReturnType<typeof usePlayer>;onPreview?:(id:string)=>void;onSample?:()=>void}){
 const d=player.data,[name,setName]=useState(d?.profile?.name||''),[listed,setListed]=useState(!!d?.profile?.listed),[discard,setDiscard]=useState(false);
 useEffect(()=>{setName(d?.profile?.name||'');setListed(!!d?.profile?.listed);},[d?.profile?.name,d?.profile?.listed]);
 const total=(d?.scores||[]).reduce((sum,s)=>sum+s.points,0)+(d?.bonusPoints||0);
 return <div className="player-panel">
 {player.error&&<p role="alert">{player.error} <button className="quiet" onClick={()=>void player.retry()} disabled={player.busy}>Retry</button></p>}
 {player.pending>0&&<p>{player.pending} account result{player.pending===1?'':'s'} waiting to sync. <button className="quiet" disabled={player.busy} onClick={()=>void player.retry()}>Retry sync</button></p>}
 {player.pending>0&&player.error&&<div><button className="quiet" disabled={player.busy} onClick={()=>{if(discard){player.discardOldest();setDiscard(false);}else setDiscard(true);}}>{discard?'Confirm: discard oldest account result':'Discard a result that cannot sync'}</button>{discard&&<p>This loses the oldest pending account score and its rewards. Your local puzzle progress stays intact. <button className="quiet" onClick={()=>setDiscard(false)}>Cancel</button></p>}</div>}
 {!d?<p>Loading player data…</p>:<>
 {!d.signedIn?<><p>Connect an account to sync your local Stardust, save future completed puzzles across devices and join the leaderboard.</p><p className="local-dust-note"><strong>✧ {player.localDust.toLocaleString()} Stardust on this device</strong><br/>It syncs automatically after you sign in. Keep this browser’s game data until syncing finishes.</p><SignInProviders/><p>Your existing guest progress stays on this device. Account points begin with puzzles completed while signed in.</p></>:<>
 {!d.profile&&<p className="local-dust-note"><strong>✧ {(d.wallet||0).toLocaleString()} Stardust saved to your account</strong>{player.localDust>0&&<> · {player.localDust} waiting to sync</>}</p>}<form onSubmit={e=>{e.preventDefault();void player.saveProfile(name,listed);}}><label>Player name<input required minLength={2} maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="Choose a public nickname"/></label><label className="player-optin"><input type="checkbox" checked={listed} onChange={e=>setListed(e.target.checked)}/> Show my nickname and statistics on the leaderboard</label><button className="primary-button" disabled={player.busy}>{d.profile?'Save profile':'Create player profile'}</button></form>
 {d.profile&&<><div className="player-stats"><strong>{total.toLocaleString()}<small>account points</small></strong><strong>{d.scores?.length||0}<small>unique puzzles</small></strong><strong>{d.stats?.completions||0}<small>completions</small></strong><strong>{d.stats?.moves||0}<small>total moves</small></strong><strong>{d.stats?.hints||0}<small>hints used</small></strong><strong>{Math.round((d.stats?.seconds||0)/60)}<small>recorded Pulse minutes</small></strong></div>
 <h3>Your streaks</h3>{!!d.stats?.completions&&<p>Welcome back. Your stars, unlocks and earned rewards are here whenever you return.</p>}<p>Complete at least one puzzle each UTC day, Monday–Sunday week, or calendar month. Bonuses are awarded once per period when a completed puzzle syncs to your account.</p><div className="streak-cards">{d.streaks?.map(s=><div key={s.kind}><strong>{s.count} {s.kind}</strong><span>{s.active?'A little light added':s.count?'Another moment when you’re ready':'A fresh start whenever you’re ready'}</span><small>{s.active?'Period bonus':'Next completion'}: +{s.bonus} points · +{dustForStreak(s.kind,s.active?s.count:s.count+1)} Stardust</small></div>)}</div><p>Daily: 50 × streak (up to 350). Weekly: 250 × streak (up to 1,000). Monthly: 1,000 × streak (up to 3,000). Earned points and Stardust stay yours. After a break, a new streak begins with your next completed puzzle.</p><StardustShop player={player} onPreview={onPreview} onSample={onSample}/></>}
 <a className="quiet" href={d.provider&&d.provider!=='chatgpt'?'/api/auth/signout?callbackUrl=%2Fsignout-with-chatgpt%3Freturn_to%3D%252F':'/signout-with-chatgpt?return_to=%2F'} target="_top">Sign out</a></>}
 {d.signedIn&&player.guestPending>0&&<p className="local-dust-note">{player.localDust} local Stardust waiting to sync. <button className="quiet" disabled={player.busy} onClick={()=>void player.retry()}>Retry Stardust sync</button></p>}<h3>Leaderboard</h3><p>Best puzzle scores + streak bonuses. Only players who choose to appear are shown.</p>
 {d.leaderboard.length?<div className="leaderboard-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Points</th><th>Puzzles</th><th>Stars</th></tr></thead><tbody>{d.leaderboard.map((p,i)=><tr key={i}><td>{i+1}</td><td>{p.name}</td><td>{p.points.toLocaleString()}</td><td>{p.puzzles}</td><td>{p.stars}</td></tr>)}</tbody></table></div>:<p>No public scores yet. Complete a puzzle and opt in to be among the first.</p>}
 <p className="helper-note">Preview leaderboard: routes and moves are checked on the server; elapsed time is reported by the game. Historical guest scores are not ranked.</p><button className="quiet" onClick={()=>void player.refresh()} disabled={player.busy}>Refresh standings</button>
 </>}
 </div>;
}
