'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Leaf,Settings2,Volume2,VolumeX,Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {relaxInstruments,restoreInstrument} from '@/lib/relax-instruments';
import {Slider} from '@/components/ui/slider';
import {relaxPuzzle,restoreRelax,relaxPaths,type RelaxSave,type RelaxSize} from '@/lib/relax';
import {rotate,ports} from '@/lib/game';
import {illuminate,explainHint} from '@/lib/journey';
import {EnergyStream} from './EnergyStream';
import {SkyMenu} from './SkyMenu';
import {useRelaxAudio} from './useRelaxAudio';
import './relax.css';
export function RelaxGame({onJourney}:{onJourney:()=>void}){
 const [save,setSave]=useState<RelaxSave>(()=>restoreRelax(null)),[loaded,setLoaded]=useState(false),[settings,setSettings]=useState(false),[sky,setSky]=useState(false),[hint,setHint]=useState<number|null>(null),[still,setStill]=useState(false),[warning,setWarning]=useState(false);
 const undo=useRef<number[][]>([]),audio=useRelaxAudio();
 const puzzle=useMemo(()=>relaxPuzzle(save.index,save.size),[save.index,save.size]),signal=useMemo(()=>illuminate(save.board,puzzle),[save.board,puzzle]);
 useEffect(()=>{try{setSave(restoreRelax(JSON.parse(localStorage.getItem('prism-relax-save')||'null')));setStill(localStorage.getItem('prism-relax-still')==='true');}catch{setWarning(true);}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('prism-relax-save',JSON.stringify(save));}catch{setWarning(true);}},[save,loaded]);
 const change=(board:number[])=>{undo.current=[...undo.current.slice(-99),save.board];setHint(null);const next=illuminate(board,puzzle);if(next.solved&&!signal.solved)audio.complete();else audio.touch();setSave(s=>({...s,board,lit:next.solved&&s.lit.length<90?[...Array.from({length:s.lit.length+1},(_,i)=>i)]:s.lit}));};
 const next=(size:RelaxSize=save.nextSize??save.size)=>{undo.current=[];setHint(null);setSave(s=>{const index=s.index>=1000000?0:s.index+1;return {...s,index,size,board:relaxPuzzle(index,size).initial};});};
 const nudge=()=>{const h=explainHint(save.board,puzzle);if(h){setHint(h.at);change(save.board.map((m,i)=>i===h.at?puzzle.solution[i]:m));setHint(h.at);}};
 const stars=Object.fromEntries(save.lit.map(i=>[String(i+1),1]));
 return <main className={'game-shell relax-shell'+(still?' still':'')} style={{'--beam':'#a6d9d5','--primary':'#a6d9d5'} as React.CSSProperties}>
 <header className="topbar"><span className="wordmark"><span className="brand-symbol">◈</span> PRISM PATH</span><div className="top-actions"><button className="icon-button" onClick={()=>setSky(true)} aria-label="Open constellation progress and star map" title="Your quiet sky"><Sparkles size={20}/></button><button className="icon-button" onClick={()=>audio.setEnabled(!audio.enabled)} aria-label={audio.enabled?'Mute ambient music':'Enable ambient music'}>{audio.enabled?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="icon-button" onClick={()=>setSettings(true)} aria-label="Relax settings"><Settings2 size={19}/></button></div></header>
 <div className="relax-layout"><div className="relax-intro"><span className="eyebrow"><Leaf size={15}/> RELAX MODE</span><h1>A little room<br/>to unwind.</h1><p>Follow the light.<br/>Take all the time you need.</p><fieldset className="relax-instruments"><legend>Music instrument</legend><RadioGroup value={audio.instrument} onValueChange={v=>audio.setInstrument(restoreInstrument(v))} aria-label="Music instrument">{relaxInstruments.map(item=><label key={item.id} className="relax-instrument"><RadioGroupItem value={item.id}/><span>{item.label}</span></label>)}</RadioGroup><p>Choose an instrument to hear it while music is on.</p></fieldset><button className="quiet" onClick={onJourney}>Return to Journey</button></div>
 <section className="relax-play" aria-label="Relaxing light puzzle">{audio.enabled&&(!audio.playing||audio.error)&&<div className="relax-audio-start"><button className="quiet" onClick={audio.start}>Start relaxing audio</button>{audio.error&&<span role="status">{audio.error}</span>}</div>}<div className="relax-caption"><h2>{signal.solved?'A peaceful connection.':'One gentle connection.'}</h2><p>{signal.solved?'Stay with the glow, or wander to another path.':'Turn a tile and let the openings meet.'}</p></div>
 <div className="board-wrap"><div className="source-label">LIGHT IN <span>→</span></div><div className={'board '+(signal.solved?'complete':'')} style={{gridTemplateColumns:`repeat(${puzzle.size},1fr)`}}>{save.board.map((mask,i)=><button key={`${save.index}-${i}`} className={'tile '+(signal.lit.has(i)?'lit ':'')+(hint===i?'relax-guided':'')} disabled={!loaded||signal.solved} onClick={()=>change(save.board.map((m,j)=>j===i?rotate(m):m))} aria-label={`Row ${Math.floor(i/puzzle.size)+1}, column ${i%puzzle.size+1}; ${ports(mask)}; ${signal.lit.has(i)?'lit':'unlit'}. Rotate clockwise.`} onKeyDown={e=>{const offset=({ArrowUp:-puzzle.size,ArrowDown:puzzle.size,ArrowLeft:-1,ArrowRight:1} as Record<string,number>)[e.key];if(offset!==undefined){e.preventDefault();const buttons=e.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('button');buttons?.[i+offset]?.focus();}}}><svg viewBox="0 0 100 100" aria-hidden="true">{[1,2,4,8].filter(b=>mask&b).map(b=><path key={b} d={`M50 50 L${b===2?100:b===8?0:50} ${b===1?0:b===4?100:50}`} className="channel"/>)}<circle cx="50" cy="50" r="4" className="node"/></svg></button>)}<EnergyStream board={save.board} puzzle={puzzle} signal={signal} color="#a6d9d5" gentle still={still}/></div><div className="target-label"><span>→</span> LIGHT OUT</div></div>
 <div className="relax-message" role="status">{signal.solved?'Nothing to chase. Just a little more light.':hint!==null?'A connection made for you. Help is always welcome.':'There is no wrong pace.'}</div>
 {signal.solved?<button className="primary-button" onClick={()=>{audio.confirmNext();next();}}>Another gentle path <ArrowRight size={17}/></button>:<div className="board-actions"><button className="quiet" disabled={!undo.current.length} onClick={()=>{const board=undo.current.pop();if(board){setHint(null);setSave(s=>({...s,board}));}}}>Undo</button><button className="hint" onClick={nudge}>Help me connect</button><button className="quiet" onClick={()=>next()}>Try another path</button></div>}
 <fieldset className="relax-paths"><legend>Where would you like to wander next?</legend><RadioGroup value={String(save.nextSize??save.size)} onValueChange={v=>setSave(s=>({...s,nextSize:Number(v) as RelaxSize}))} aria-label="Next Relax path style">{relaxPaths.map(path=><label key={path.size} className="relax-path-choice"><RadioGroupItem value={String(path.size)}/><span>{path.label}<small>{path.description}</small></span></label>)}</RadioGroup><p>Your choice begins with the next path. Help and skipping are always available.</p></fieldset><p className="relax-footnote">No timer. No score. No need to finish.</p>{warning&&<p role="status">Your browser cannot save this quiet journey right now.</p>}</section></div>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="game-dialog relax-dialog"><DialogTitle>Make yourself comfortable.</DialogTitle><DialogDescription>Relax Mode keeps a separate quiet sky on this device. Your Journey progress stays safe.</DialogDescription><div className="calm-setting"><label htmlFor="relax-music">Ambient music</label><Switch id="relax-music" checked={audio.enabled} onCheckedChange={audio.setEnabled}/></div><div className="relax-size" aria-label="Preview sound effects"><button className="quiet" disabled={!audio.effects} onClick={()=>audio.touch()}>Preview tile sound</button><button className="quiet" disabled={!audio.effects} onClick={audio.complete}>Preview completion</button><button className="quiet" disabled={!audio.effects} onClick={audio.confirmNext}>Preview next puzzle</button></div><p className="audio-note">{audio.playing?'Ambient music is playing.':audio.enabled?'Tap Start relaxing audio to begin playback.':'Ambient music is muted.'} Your device volume also controls what you hear.</p><label id="relax-volume">Music volume</label><Slider aria-labelledby="relax-volume" value={[audio.volume*100]} min={0} max={100} step={1} onValueChange={v=>audio.setVolume((Array.isArray(v)?v[0]:v)/100)}/><div className="calm-setting"><label htmlFor="relax-sounds">Sound effects</label><Switch id="relax-sounds" checked={audio.effects} onCheckedChange={audio.setEffects}/></div><div className="calm-setting"><label htmlFor="relax-still">Still light · no animation</label><Switch id="relax-still" checked={still} onCheckedChange={v=>{setStill(v);try{localStorage.setItem('prism-relax-still',String(v));}catch{}}}/></div><p>Reduced motion also follows your device setting.</p><button className="quiet" onClick={onJourney}>Return to Journey</button></DialogContent></Dialog>
 <Dialog open={sky} onOpenChange={setSky}><DialogContent className="game-dialog relax-dialog"><DialogTitle>Your quiet sky.</DialogTitle><DialogDescription>A little light from the paths you’ve enjoyed. Come back whenever you feel like it.</DialogDescription><SkyMenu stars={stars}/></DialogContent></Dialog>
 </main>;
}
