import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {enrich,illuminate,explainHint,canPlay,paceBudget,type JourneyPuzzle} from '../lib/journey.ts';
import {turnsTo} from '../lib/game.ts';
const bank=JSON.parse(readFileSync(new URL('../lib/content/puzzles.json',import.meta.url),'utf8'));
test('Exit and receiver light cannot bypass a required locked tile',()=>{const p:JourneyPuzzle={id:11,stage:11,paceSeconds:0,size:2,initial:[10,12,1,3],solution:[14,12,1,3],path:[0,1,3,2],par:1,locked:[2],filters:{},receivers:[{at:3,color:'mint'}],lesson:''};const bypass=illuminate(p.initial,p);assert.ok(bypass.lit.has(3));assert.equal(bypass.received,1);assert.equal(bypass.solved,false);assert.match(explainHint(p.initial,p)!.text,/locked tile/);assert.equal(illuminate(p.solution,p).solved,true);p.locked.push(1);assert.equal(illuminate(p.solution,p).solved,true);});
test('Every revised campaign and daily puzzle has a valid reachable solution',()=>{for(const base of [...bank.campaign,...bank.daily]){const p=enrich(base);assert.ok(illuminate(p.solution,p).solved,`solution ${p.id}`);assert.ok(!illuminate(p.initial,p).solved,`initial ${p.id}`);for(const i of p.locked)assert.equal(p.initial[i],p.solution[i]);assert.equal(p.par,p.path.reduce((n,i)=>n+turnsTo(p.initial[i],p.solution[i]),0));let board=[...p.initial];for(let i=0;i<board.length&&!illuminate(board,p).solved;i++){const hint=explainHint(board,p);assert.ok(hint,`hint ${p.id}`);assert.ok(!p.locked.includes(hint.at));board[hint.at]=p.solution[hint.at];}assert.ok(illuminate(board,p).solved,`hints solve ${p.id}`);}});
test('Opening lessons use three small boards and a gradually longer repair',()=>{const first=bank.campaign.slice(0,3).map(enrich);assert.deepEqual(first.map((p:JourneyPuzzle)=>p.size),[3,3,3]);assert.deepEqual(first.map((p:JourneyPuzzle)=>p.initial.filter((m,i)=>m!==p.solution[i]).length),[1,2,3]);});
test('A reachable exit is insufficient when a receiver is dark or the wrong color',()=>{const p:JourneyPuzzle={stage:1,paceSeconds:0,id:1,size:2,initial:[10,12,0,3],solution:[10,12,0,3],path:[0,1,3],par:0,locked:[],filters:{},receivers:[{at:3,color:'amber'}],lesson:''};assert.equal(illuminate(p.solution,p).solved,false);p.filters[1]='amber';assert.equal(illuminate(p.solution,p).solved,true);p.receivers.push({at:2,color:'mint'});assert.equal(illuminate(p.solution,p).solved,false);});
test('Three samples are free; later content needs a preview unlock and progress',()=>{assert.ok(canPlay(30,{},false));assert.ok(canPlay(31,{'31':1},false));assert.ok(canPlay(32,{'32':1},false));assert.ok(!canPlay(33,{'33':1},false));assert.ok(canPlay(33,{'33':1},true));assert.ok(!canPlay(32,{},false));assert.ok(canPlay(3,{'4':2},false));assert.ok(!canPlay(90,{},true));});

test('Mechanics arrive one stage at a time and daily puzzles stay simple',()=>{const puzzles=bank.campaign.map(enrich);for(const p of puzzles.slice(0,10)){assert.equal(p.locked.length,0);assert.equal(p.receivers.length,0);assert.equal(Object.keys(p.filters).length,0);assert.equal(p.paceSeconds,0);}for(const p of puzzles.slice(10,20)){assert.equal(p.receivers.length,0);assert.equal(Object.keys(p.filters).length,0);}assert.ok(puzzles[20].receivers.length>0);assert.equal(Object.keys(puzzles[39].filters).length,0);assert.equal(Object.keys(puzzles[40].filters).length,1);assert.equal(Object.keys(puzzles[60].filters).length,2);for(const b of bank.daily){const p=enrich(b);assert.equal(p.receivers.length,0);assert.equal(Object.keys(p.filters).length,0);}});
test('Bonus pace tightens for equally long routes without imposing an early timer',()=>{assert.equal(paceBudget(10,20),0);assert.ok(paceBudget(11,20)>paceBudget(41,20));assert.ok(paceBudget(41,20)>paceBudget(90,20));assert.ok(paceBudget(90,1)>=25);});
